version: "3"

services:
  redis:
    image: redis:7.0.11-alpine
  liquidsoap:
    image: ghcr.io/lumiradio/liquidsoap
    build:
      context: ./docker/liquidsoap
      dockerfile: Dockerfile
      args:
        - OPAM_PACKAGES=liquidsoap.2.0.0 taglib mad lame vorbis cry samplerate ocurl
    volumes:
      - ./docker/liquidsoap/script.liq:/etc/liquidsoap/script.liq
      - ./docker/liquidsoap/vars.json:/etc/liquidsoap/vars.json
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music
      - ls_socket:/etc/liquidsoap
    environment:
      ICECAST_HOST: ${ICECAST_HOST}
      ICECAST_PORT: ${ICECAST_PORT}
      ICECAST_USER: ${ICECAST_USER}
      ICECAST_PASSWORD: ${ICECAST_PASSWORD}
      ICECAST_MOUNT: ${ICECAST_MOUNT}
      LANGLEY_URL: http://langley:8000/played
  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
  byers:
    image: ghcr.io/lumiradio/byers
    build:
      context: ./byers
      dockerfile: Dockerfile
    depends_on:
      - liquidsoap
    environment:
      DISCORD_TOKEN: ${BYERS_DISCORD_TOKEN}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}
      LIQUIDSOAP__HOST: liquidsoap
      LIQUIDSOAP__PORT: 1234
      GOOGLE__CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE__CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REDIS_URL: redis://redis/
      RUST_LOG: info
    volumes:
      - ls_socket:/usr/src/app/ls
  langley:
    image: ghcr.io/lumiradio/langley
    build:
      context: ./langley
      dockerfile: Dockerfile
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_DATABASES: '{byersdb={url="postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}"}}'
      REDIS_URL: redis://redis/
  frohike:
    image: ghcr.io/lumiradio/frohike
    build:
      context: ./frohike
      dockerfile: Dockerfile
    environment:
      RUST_LOG: debug
      REDIS_URL: redis://redis/
    command:
      - "house-keeping"
      - "--database-url"
      - "postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}"
      - "/music"
    volumes:
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music

volumes:
  pg_data:
  liquidsoap:
  ls_socket:
