version: "3"

services:
  redis:
    image: redis:7.0.11-alpine
  liquidsoap:
    image: ghcr.io/lumiradio/liquidsoap:${LIQUIDSOAP_TAG}
    command: ["/usr/share/liquidsoap/script.liq"]
    build:
      context: ./docker/liquidsoap
      dockerfile: Dockerfile
    volumes:
      - ./docker/liquidsoap/script.liq:/usr/share/liquidsoap/script.liq
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music:ro
      - ls_socket:/usr/share/liquidsoap
    environment:
      ICECAST_HOST: ${ICECAST_HOST}
      ICECAST_PORT: ${ICECAST_PORT}
      ICECAST_USER: ${ICECAST_USER}
      ICECAST_PASSWORD: ${ICECAST_PASSWORD}
      ICECAST_MOUNT: ${ICECAST_MOUNT}
      LANGLEY_URL: http://langley:8000/played
  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
  byers:
    image: ghcr.io/lumiradio/lumiradio:${BYERS_TAG}
    command: "./byers/byers"
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 8181:8000
    depends_on:
      - liquidsoap
    environment:
      DISCORD_TOKEN: ${BYERS_DISCORD_TOKEN}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}
      LIQUIDSOAP__HOST: liquidsoap
      LIQUIDSOAP__PORT: 1234
      GOOGLE__CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE__CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DISCORD__CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD__CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      SECRET: ${SECRET}
      REDIS_URL: redis://redis/
      RUST_LOG: info
    volumes:
      - ls_socket:/usr/src/app/ls
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music
  langley:
    image: ghcr.io/lumiradio/lumiradio:${LANGLEY_TAG}
    command: "./langley/langley"
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}
      REDIS_URL: redis://redis/
      RUST_LOG: info
  frohike:
    image: ghcr.io/lumiradio/lumiradio:${FROHIKE_TAG}
    environment:
      RUST_LOG: debug
      REDIS_URL: redis://redis/
    command:
      - "./frohike/frohike"
      - "house-keeping"
      - "--database-url"
      - "postgres://${PG_USER}:${PG_PASSWORD}@db/${PG_DATABASE}"
      - "/music"
    volumes:
      - ${RADIO_MUSIC:?RADIO_MUSIC is unset}:/music

volumes:
  pg_data:
  liquidsoap:
  ls_socket:
