//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod bp_counters;
pub mod cans;
pub mod connected_youtube_accounts;
pub mod favourite_songs;
pub mod played_songs;
pub mod server_channel_config;
pub mod server_config;
pub mod server_role_config;
pub mod slcb_currency;
pub mod slcb_rank;
pub mod song_requests;
pub mod song_tags;
pub mod users;
