//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod api_keys;
pub mod cans;
pub mod connected_youtube_accounts;
pub mod favourite_songs;
pub mod played_songs;
pub mod server_channel_config;
pub mod server_config;
pub mod server_role_config;
pub mod slcb_currency;
pub mod slcb_rank;
pub mod song_requests;
pub mod song_tags;
pub mod songs;
pub mod token_storage;
pub mod users;
