//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::bp_counters::Entity as BpCounters;
pub use super::cans::Entity as Cans;
pub use super::connected_youtube_accounts::Entity as ConnectedYoutubeAccounts;
pub use super::favourite_songs::Entity as FavouriteSongs;
pub use super::played_songs::Entity as PlayedSongs;
pub use super::server_channel_config::Entity as ServerChannelConfig;
pub use super::server_config::Entity as ServerConfig;
pub use super::server_role_config::Entity as ServerRoleConfig;
pub use super::slcb_currency::Entity as SlcbCurrency;
pub use super::slcb_rank::Entity as SlcbRank;
pub use super::song_requests::Entity as SongRequests;
pub use super::song_tags::Entity as SongTags;
pub use super::users::Entity as Users;
