[package]
name = "byers"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
config = "0.15"
poise = { version = "0.6" }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-unwrap = { version = "1.0", features = ["log-location"] }
lazy_static = "1.4.0"
fred = { version = "10.1", features = ["subscriber-client"] }
async-trait = "0.1.71"
num-traits = "0.2.15"
strum = { version = "0.27", features = ["derive"] }
rand = "0.9"
anyhow = { version = "1.0.72", features = ["backtrace"] }
thiserror = "2.0"
tokio-stream = "0.1.14"
once_cell = "1.18.0"
async-fred-session = "0.1.5"
oauth2 = "5.0"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde_repr = "0.1.16"
futures = "0.3.28"
ellipse = "0.2.0"
situwaition = { version = "0.3.2", features = ["tokio"] }
serde_json = "1.0.107"
judeharley = { path = "../judeharley" }
sentry = { version = "0.37" }
sentry-anyhow = { version = "0.37", features = ["backtrace"] }
clokwerk = "0.4.0"
