/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/discord/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["discord_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A request to log in with Discord, part of the OAuth 2.0 flow
         *
         *     This will be used to exchange the authorization code for an access token */
        DiscordLoginRequest: {
            /** @description The authorization code received from Discord */
            code: string;
        };
        DiscordLoginResponse: {
            /** Format: int64 */
            expires_at: number;
            /** Format: int64 */
            expires_in: number;
            token: string;
            /** Format: int64 */
            user_id: number;
        };
        /** @description An error response containing details about the problem */
        ErrorResponse: {
            /** @description A machine-readable error code */
            error: string;
            /** @description A human-readable message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    discord_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscordLoginRequest"];
            };
        };
        responses: {
            /** @description Discord login was successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscordLoginResponse"];
                };
            };
            /** @description An authorization error occurred (e.g. invalid authorization code) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An internal server error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
