[package]
name = "caliborn"
description = "API server for lumiRadio"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
axum = { version = "0.8.3", features = ["macros", "ws"] }
chrono = "0.4.40"
figment = { version = "0.10.19", features = ["env"] }
hmac = "0.12.1"
jwt = "0.16.0"
oauth2 = "5.0.0"
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
url = "2.5.4"
serenity = "0.12.4"
utoipa = { version = "5.3.1", features = ["axum_extras", "chrono"] }
axum-macros = "0.5.0"
utoipa-swagger-ui = { version = "9.0.1", features = ["axum"] }
sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
    "with-rust_decimal",
] }
migration = { path = "../migration" }
sea-query = "0.32.4"
async-trait = "0.1.88"
rand = "0.9.1"
prefixed-api-key = { version = "0.3.0", features = ["all"] }
tracing = "0.1.41"
hex = "0.4.3"
subtle = "2.6.1"
anyhow = "1.0.98"
tracing-unwrap = "1.0.1"
serde_json = "1.0.140"
