//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub watched_time: i64,
    pub boonbucks: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_message_sent: Option<DateTime>,
    pub migrated: bool,
    pub username: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::cans::Entity")]
    Cans,
    #[sea_orm(has_many = "super::connected_youtube_accounts::Entity")]
    ConnectedYoutubeAccounts,
    #[sea_orm(has_many = "super::favourite_songs::Entity")]
    FavouriteSongs,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::cans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cans.def()
    }
}

impl Related<super::connected_youtube_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConnectedYoutubeAccounts.def()
    }
}

impl Related<super::favourite_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FavouriteSongs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
