[alias]
addm = "sqlx migrate add --source judeharley/migrations -r "
runm = "sqlx migrate run --source judeharley/migrations -D postgres://byers:byers@localhost/byers"
revertm = "sqlx migrate revert --source judeharley/migrations -D postgres://byers:byers@localhost/byers"
